[build]
  base    = "gatsby"
  publish = "gatsby/public"
  command = "yarn build"

[[redirects]]
  from = "https://www.mattboldt.com/*"
  to = "https://mattboldt.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/typed.js/*"
  to = "https://mattboldt.github.io/typed.js/:splat"
  status = 301
  force = true
